# Generated by Django 5.2.7 on 2025-11-06 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_url', models.URLField(max_length=500, verbose_name='Repository URL')),
                ('repository_owner', models.CharField(max_length=255, verbose_name='Repository Owner')),
                ('repository_name', models.CharField(max_length=255, verbose_name='Repository Name')),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='Scan Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('total_files_scanned', models.IntegerField(default=0, verbose_name='Total Files Scanned')),
                ('secrets_found_count', models.IntegerField(default=0, verbose_name='Secrets Found')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Repository Scan',
                'verbose_name_plural': 'Repository Scans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecretFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1000, verbose_name='File Path')),
                ('line_number', models.IntegerField(verbose_name='Line Number')),
                ('secret_type', models.CharField(choices=[('aws_access_key', 'AWS Access Key'), ('aws_secret_key', 'AWS Secret Key'), ('github_token', 'GitHub Token'), ('generic_api_key', 'Generic API Key'), ('private_key', 'Private Key'), ('password', 'Password'), ('slack_token', 'Slack Token'), ('stripe_key', 'Stripe Key'), ('google_api_key', 'Google API Key'), ('jwt_token', 'JWT Token'), ('generic_secret', 'Generic Secret'), ('database_url', 'Database URL'), ('oauth_token', 'OAuth Token')], db_index=True, max_length=50, verbose_name='Secret Type')),
                ('matched_pattern', models.CharField(max_length=200, verbose_name='Matched Pattern')),
                ('context_snippet', models.TextField(verbose_name='Context Snippet')),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', max_length=10, verbose_name='Severity')),
                ('is_false_positive', models.BooleanField(default=False, verbose_name='Is False Positive')),
                ('false_positive_reason', models.TextField(blank=True, verbose_name='False Positive Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scanner.repositoryscan', verbose_name='Scan')),
            ],
            options={
                'verbose_name': 'Secret Finding',
                'verbose_name_plural': 'Secret Findings',
                'ordering': ['-severity', 'file_path', 'line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='repositoryscan',
            index=models.Index(fields=['-created_at', 'scan_status'], name='scanner_rep_created_aaebfb_idx'),
        ),
        migrations.AddIndex(
            model_name='secretfinding',
            index=models.Index(fields=['scan', 'secret_type'], name='scanner_sec_scan_id_deeddf_idx'),
        ),
        migrations.AddIndex(
            model_name='secretfinding',
            index=models.Index(fields=['scan', 'severity'], name='scanner_sec_scan_id_7b5f4e_idx'),
        ),
    ]
