# Generated by Django 5.2.7 on 2025-11-07 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryscan',
            name='commit_date',
            field=models.DateTimeField(blank=True, help_text='Date of the commit that was scanned', null=True, verbose_name='Commit Date'),
        ),
        migrations.AddField(
            model_name='repositoryscan',
            name='commit_sha',
            field=models.CharField(blank=True, db_index=True, help_text='Git commit SHA that was scanned', max_length=40, verbose_name='Commit SHA'),
        ),
        migrations.AddIndex(
            model_name='repositoryscan',
            index=models.Index(fields=['repository_owner', 'repository_name', 'commit_sha'], name='scanner_rep_reposit_4d220e_idx'),
        ),
    ]
