# Generated by Django 5.2.7 on 2025-11-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_repositoryscan_commit_date_repositoryscan_commit_sha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryscan',
            name='github_issue_number',
            field=models.IntegerField(blank=True, help_text='GitHub issue number if findings were reported', null=True, verbose_name='GitHub Issue Number'),
        ),
        migrations.AddField(
            model_name='repositoryscan',
            name='github_issue_url',
            field=models.URLField(blank=True, help_text='URL to the GitHub issue created for this scan', max_length=500, verbose_name='GitHub Issue URL'),
        ),
        migrations.AddField(
            model_name='repositoryscan',
            name='issue_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Issue Created At'),
        ),
    ]
