# Generated by Django 5.2.7 on 2025-11-09 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_repositoryscan_github_issue_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_url', models.URLField(max_length=500, unique=True, verbose_name='Repository URL')),
                ('repository_owner', models.CharField(max_length=255, verbose_name='Repository Owner')),
                ('repository_name', models.CharField(max_length=255, verbose_name='Repository Name')),
                ('scan_interval', models.IntegerField(choices=[(3600, 'Every Hour'), (21600, 'Every 6 Hours'), (86400, 'Daily'), (604800, 'Weekly')], default=86400, help_text='How often to scan this repository', verbose_name='Scan Interval (seconds)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this repository should be scanned', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_scanned_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last Scanned At')),
                ('next_scan_at', models.DateTimeField(blank=True, db_index=True, help_text='When the next scan should occur', null=True, verbose_name='Next Scan At')),
                ('total_scans', models.IntegerField(default=0, verbose_name='Total Scans')),
                ('last_secrets_found', models.IntegerField(default=0, verbose_name='Last Secrets Found')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchlist_repositories', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('last_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchlist_entries', to='scanner.repositoryscan', verbose_name='Last Scan')),
            ],
            options={
                'verbose_name': 'Repository Watchlist',
                'verbose_name_plural': 'Repository Watchlists',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'next_scan_at'], name='scanner_rep_is_acti_3a8264_idx'), models.Index(fields=['repository_owner', 'repository_name'], name='scanner_rep_reposit_315bcb_idx')],
            },
        ),
    ]
